language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO='Django==1.11.*'
  - DJANGO='Django==2.0.*'
  - DJANGO='Django==2.1.*'
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
      env: DJANGO='Django==1.11.*'
    - python: "3.7"
      dist: xenial
      sudo: true
      env: DJANGO='Django==2.0.*'
    - python: "3.7"
      dist: xenial
      sudo: true
      env: DJANGO='Django==2.1.*'
  exclude:
    - python: "2.7"
      env: DJANGO='Django==2.0.*'
    - python: "2.7"
      env: DJANGO='Django==2.1.*'
install:
  - pip install $DJANGO
script:
  - make test
